Return-Path: <linux-mediatek-bounces+lists+linux-mediatek=lfdr.de@lists.infradead.org>
X-Original-To: lists+linux-mediatek@lfdr.de
Delivered-To: lists+linux-mediatek@lfdr.de
Received: from bombadil.infradead.org (bombadil.infradead.org [IPv6:2607:7c80:54:e::133])
	by mail.lfdr.de (Postfix) with ESMTPS id E93901B3684
	for <lists+linux-mediatek@lfdr.de>; Wed, 22 Apr 2020 06:46:54 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed;
	d=lists.infradead.org; s=bombadil.20170209; h=Sender:
	Content-Transfer-Encoding:Content-Type:Cc:List-Subscribe:List-Help:List-Post:
	List-Archive:List-Unsubscribe:List-Id:MIME-Version:To:Subject:From:Message-ID
	:Date:Reply-To:Content-ID:Content-Description:Resent-Date:Resent-From:
	Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID:In-Reply-To:References:
	List-Owner; bh=cTvsY63ONeEEN05piL01oklaqap6ySf58M7LDR0NMUA=; b=FRvm5iht5NMAUd
	dddYhCsVcqNKVcLPVfzr5GJBio4RKTUtjBIhlA4Yh7wJWAKoT6aUdm3Yl+dmAm7WfDuQSJUHOs4a2
	z2K+GmajGzao7OjutUZJXZiB3TVgFGd7LqWxblozCMA+IQnU6KUiOoURkmtxSDBxFdkjxdGF9kq+7
	H7Jq62QVTx/1fY87vO583IjzUPKaVMry99+fQMl2I3boxpz8hgSGlIljs9nMNWn4kb8ue7lk+BSMJ
	I4AkKzLtwQOG6I+RP0bI1RecRA7IpxcGw+wrIL8nSimv8PXhs33EfQarlzXFZYxiw/iZaSqAkf1nr
	Z+gwN/imyX/CiPTfUShA==;
Received: from localhost ([127.0.0.1] helo=bombadil.infradead.org)
	by bombadil.infradead.org with esmtp (Exim 4.92.3 #3 (Red Hat Linux))
	id 1jR7HZ-0006Co-6M; Wed, 22 Apr 2020 04:46:45 +0000
Received: from relmlor1.renesas.com ([210.160.252.171]
 helo=relmlie5.idc.renesas.com)
 by bombadil.infradead.org with esmtp (Exim 4.92.3 #3 (Red Hat Linux))
 id 1jR7HO-00066E-Cs; Wed, 22 Apr 2020 04:46:36 +0000
Date: 22 Apr 2020 13:46:30 +0900
X-IronPort-AV: E=Sophos;i="5.72,412,1580742000"; d="scan'208";a="45382248"
Received: from unknown (HELO relmlir6.idc.renesas.com) ([10.200.68.152])
 by relmlie5.idc.renesas.com with ESMTP; 22 Apr 2020 13:46:30 +0900
Received: from mercury.renesas.com (unknown [10.166.252.133])
 by relmlir6.idc.renesas.com (Postfix) with ESMTP id 10BF341C17D7;
 Wed, 22 Apr 2020 13:46:30 +0900 (JST)
Message-ID: <87d080unyx.wl-kuninori.morimoto.gx@renesas.com>
From: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
Subject: [PATCH 0/4] ASoC:: don't use snd_soc_rtdcom_lookup()
User-Agent: Wanderlust/2.15.9 Emacs/25.2 Mule/6.0
To: Mark Brown <broonie@kernel.org>
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
X-CRM114-Version: 20100106-BlameMichelson ( TRE 0.8.0 (BSD) ) MR-646709E3 
X-CRM114-CacheID: sfid-20200421_214634_548867_BF2EC2C0 
X-CRM114-Status: UNSURE (   8.21  )
X-CRM114-Notice: Please train this message.
X-Spam-Score: 0.0 (/)
X-Spam-Report: SpamAssassin version 3.4.4 on bombadil.infradead.org summary:
 Content analysis details:   (0.0 points)
 pts rule name              description
 ---- ---------------------- --------------------------------------------------
 -0.0 RCVD_IN_DNSWL_NONE     RBL: Sender listed at https://www.dnswl.org/,
 no trust [210.160.252.171 listed in list.dnswl.org]
 -0.0 SPF_PASS               SPF: sender matches SPF record
 0.0 SPF_HELO_NONE          SPF: HELO does not publish an SPF Record
 0.0 AC_FROM_MANY_DOTS      Multiple periods in From user name
X-BeenThere: linux-mediatek@lists.infradead.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <linux-mediatek.lists.infradead.org>
List-Unsubscribe: <http://lists.infradead.org/mailman/options/linux-mediatek>, 
 <mailto:linux-mediatek-request@lists.infradead.org?subject=unsubscribe>
List-Archive: <http://lists.infradead.org/pipermail/linux-mediatek/>
List-Post: <mailto:linux-mediatek@lists.infradead.org>
List-Help: <mailto:linux-mediatek-request@lists.infradead.org?subject=help>
List-Subscribe: <http://lists.infradead.org/mailman/listinfo/linux-mediatek>, 
 <mailto:linux-mediatek-request@lists.infradead.org?subject=subscribe>
Cc: Kate Stewart <kstewart@linuxfoundation.org>,
 Cezary Rojewski <cezary.rojewski@intel.com>,
 Jie Yang <yang.jie@linux.intel.com>, alsa-devel@alsa-project.org,
 Jaroslav Kysela <perex@perex.cz>,
 Liam Girdwood <liam.r.girdwood@linux.intel.com>,
 Richard Fontana <rfontana@redhat.com>, Shunli Wang <shunli.wang@mediatek.com>,
 YueHaibing <yuehaibing@huawei.com>,
 Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>,
 Jiaxin Yu <jiaxin.yu@mediatek.com>, linux-arm-kernel@lists.infradead.org,
 Vijendar Mukunda <Vijendar.Mukunda@amd.com>,
 Stephen Boyd <swboyd@chromium.org>, linux-mediatek@lists.infradead.org,
 Eason Yen <eason.yen@mediatek.com>, Matthias Brugger <matthias.bgg@gmail.com>,
 Thomas Gleixner <tglx@linutronix.de>, Allison Randal <allison@lohutok.net>,
 Takashi Iwai <tiwai@suse.com>,
 Ravulapati Vishnu vardhan rao <Vishnuvardhanrao.Ravulapati@amd.com>,
 Colin Ian King <colin.king@canonical.com>
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: 7bit
Sender: "Linux-mediatek" <linux-mediatek-bounces@lists.infradead.org>
Errors-To: linux-mediatek-bounces+lists+linux-mediatek=lfdr.de@lists.infradead.org


Hi Mark
Cc related engineer

These patches are tring to not to use snd_soc_rtdcom_lookup() function
on each drivers as much as possible,  because we might have same name
component under multi component situation.
It can't find correct component in such case.

I tried to add new feature on each drivers to not to use it,
but I can't test.
Thus, these patches should get Acked-by or Tested-by from each drivers
user/maintenor. Please test these.

After these patches, Intel / SOF drivers are still using
snd_soc_rtdcom_lookup(). Because it is very complex, I couldn't try
not to use it.
If possible, each drivers should try to not use it,
and it should be removed from ASoC.

Kuninori Morimoto (4):
  ASoC: mediatek: don't use snd_soc_rtdcom_lookup()
  ASoC: intel: baytrail: don't use snd_soc_rtdcom_lookup()
  ASoC: intel: haswell: don't use snd_soc_rtdcom_lookup()
  ASoC: amd: don't use snd_soc_rtdcom_lookup()

 sound/soc/amd/raven/acp3x-pcm-dma.c         |  6 ------
 sound/soc/intel/baytrail/sst-baytrail-pcm.c | 13 +++++++------
 sound/soc/intel/haswell/sst-haswell-pcm.c   |  4 +++-
 sound/soc/mediatek/common/mtk-afe-fe-dai.c  | 12 +++++-------
 sound/soc/mediatek/common/mtk-afe-fe-dai.h  |  3 ++-
 sound/soc/mediatek/common/mtk-base-afe.h    |  6 ++++--
 sound/soc/mediatek/mt2701/mt2701-afe-pcm.c  |  6 ++++--
 sound/soc/mediatek/mt6797/mt6797-afe-pcm.c  | 11 ++++-------
 sound/soc/mediatek/mt8173/mt8173-afe-pcm.c  |  7 ++++---
 sound/soc/mediatek/mt8183/mt8183-afe-pcm.c  | 11 ++++-------
 10 files changed, 37 insertions(+), 42 deletions(-)

-- 
2.17.1


_______________________________________________
Linux-mediatek mailing list
Linux-mediatek@lists.infradead.org
http://lists.infradead.org/mailman/listinfo/linux-mediatek
